# Generated by Django 5.0.6 on 2025-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, help_text='List certifications with issuing organization'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, help_text='Describe projects, technologies used, and outcomes'),
        ),
    ]
